CREATE DATABASE SOFTWARE_IPJ;

USE SOFTWARE_IPJ;

CREATE TABLE MEMBRO(
	ID_MEMBRO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(60) NOT NULL,
	COMUNGANTE BOOLEAN NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	NOME_PAI VARCHAR(60) NOT NULL,
	NOME_MAE VARCHAR(60) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	ESCOLARIDADE VARCHAR(25),
	PROFISSAO VARCHAR(25),
	NUMERO_DE_ROL INT NOT NULL,
	EMAIL VARCHAR(50),
	TELEFONE VARCHAR(15),
	CELULAR VARCHAR(15) NOT NULL,
	FOTO_MEMBRO VARCHAR(200),
    ESTADO_CIVIL VARCHAR(24));
CREATE TABLE ENDERECO(
	ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	ID_MEMBRO INT,
	CEP VARCHAR(9),
	ENDERECO VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(25) NOT NULL,
	COMPLEMENTO VARCHAR(20),
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	LOCAL_RESIDENCIA VARCHAR(4) NOT NULL,
	LOCAL_NASCIMENTO VARCHAR(30) NOT NULL,
	ESTADO_NASCIMENTO CHAR(3) NOT NULL,
FOREIGN KEY (ID_MEMBRO) REFERENCES MEMBRO(ID_MEMBRO));


CREATE TABLE ELEICAO_DIACONO(
	ID_ELEICAO_DIACONO INT PRIMARY KEY AUTO_INCREMENT,
	DATA_ELEICAO DATE,
	REELEICAO_1 DATE,
	REELEICAO_2 DATE,
	REELEICAO_3 DATE,
	REELEICAO_4 DATE,
	ID_MEMBRO INT,
	FOREIGN KEY (ID_MEMBRO) REFERENCES MEMBRO(ID_MEMBRO));

CREATE TABLE ELEICAO_PRESBITERO(
	ID_ELEICAO_PRESBITERO INT PRIMARY KEY AUTO_INCREMENT,
	DATA_ELEICAO_PRESBITERO_1 DATE,
	DATA_ELEICAO_PRESBITERO_2 DATE,
	DATA_ELEICAO_PRESBITERO_3 DATE,
	DATA_ELEICAO_PRESBITERO_4 DATE,
	ID_MEMBRO INT,
	FOREIGN KEY (ID_MEMBRO) REFERENCES MEMBRO(ID_MEMBRO));

CREATE TABLE BATISMO(
	ID_BATISMO INT PRIMARY KEY AUTO_INCREMENT,
	DATA_BATISMO DATE,
	NOME_OFICIANTE VARCHAR(50),
	ID_MEMBRO INT,
	FOREIGN KEY (ID_MEMBRO) REFERENCES MEMBRO(ID_MEMBRO));

CREATE TABLE PROFISSAO_DE_FE(
	ID_PROFISSAO_DE_FE INT PRIMARY KEY AUTO_INCREMENT,
	DATA_PROFISSAO_DE_FE DATE,
	NOME_OFICIANTE VARCHAR(50),
	ID_MEMBRO INT,
	FOREIGN KEY (ID_MEMBRO) REFERENCES MEMBRO(ID_MEMBRO));

CREATE TABLE ADMISSAO(
	ID_ADMISSAO INT PRIMARY KEY AUTO_INCREMENT,
	DATA_ADMISSAO DATE,
	FORMA_ADMISSAO VARCHAR(30),
	NUMERO_ATA INT,
	ID_MEMBRO INT,
	FOREIGN KEY (ID_MEMBRO) REFERENCES MEMBRO(ID_MEMBRO));

CREATE TABLE DEMISSAO(
	ID_DEMISSAO INT PRIMARY KEY AUTO_INCREMENT,
	DATA_DEMISSAO DATE,
	FORMA_DEMISSAO VARCHAR(30),
	NUMERO_ATA INT,
	ID_MEMBRO INT,
	FOREIGN KEY (ID_MEMBRO) REFERENCES MEMBRO(ID_MEMBRO));


CREATE TABLE ROL_SEPARADO(
	ID_ROL_SEPARADO INT PRIMARY KEY AUTO_INCREMENT,
	DATA_ROL_SEPARADO DATE,
	ATA_ROL_SEPARADO INT,
	CASAMENTO DATE,
	DISPLINA VARCHAR(10),
	DATA_DISCIPLINA DATE,
	ATA_DISCIPLINA INT,
	ID_MEMBRO INT,
	FOREIGN KEY (ID_MEMBRO) REFERENCES MEMBRO(ID_MEMBRO));
	
CREATE TABLE SOCIEDADE_INTERNA(
	ID_SOCIEDADE_INTERNA INT PRIMARY KEY AUTO_INCREMENT,
	NOME_SOCIEDADE VARCHAR(50) NOT NULL,
	FOTO_SOCIEDADE VARCHAR(200));
	
CREATE TABLE MEMBRO_SOCIEDADE(
    ID_MEMBRO_SOCIEDADE INT PRIMARY KEY AUTO_INCREMENT,
    ID_MEMBRO INT,
    ID_SOCIEDADE_INTERNA INT,
    FOREIGN KEY (ID_MEMBRO) REFERENCES MEMBRO(ID_MEMBRO),
    FOREIGN KEY (ID_SOCIEDADE_INTERNA) REFERENCES SOCIEDADE_INTERNA(ID_SOCIEDADE_INTERNA));

CREATE TABLE LOGIN(
ID_LOGIN INT PRIMARY KEY AUTO_INCREMENT,
USUARIO VARCHAR(50) NOT NULL,
SENHA VARCHAR(100) NOT NULL);

INSERT INTO LOGIN (USUARIO, SENHA) VALUES ("ipj","ipj");